// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJyiOcJJSdovm9JLkfdFP0ooBFoCiy4CU',
    appId: '1:936565713332:web:31da719a4f06149887aae1',
    messagingSenderId: '936565713332',
    projectId: 'seminarium-ecc72',
    authDomain: 'seminarium-ecc72.firebaseapp.com',
    storageBucket: 'seminarium-ecc72.appspot.com',
    measurementId: 'G-GHC192EPFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDvzpls9y-bE1FYmNAFgP5j8iZRfRnON0',
    appId: '1:936565713332:android:d6aa3eada05228eb87aae1',
    messagingSenderId: '936565713332',
    projectId: 'seminarium-ecc72',
    storageBucket: 'seminarium-ecc72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2WP3L_I6DFVMRixFypQEy6yqV0n1GKZg',
    appId: '1:936565713332:ios:bac278ebb5c8472f87aae1',
    messagingSenderId: '936565713332',
    projectId: 'seminarium-ecc72',
    storageBucket: 'seminarium-ecc72.appspot.com',
    iosBundleId: 'com.example.seminarium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2WP3L_I6DFVMRixFypQEy6yqV0n1GKZg',
    appId: '1:936565713332:ios:ada844a1b364990287aae1',
    messagingSenderId: '936565713332',
    projectId: 'seminarium-ecc72',
    storageBucket: 'seminarium-ecc72.appspot.com',
    iosBundleId: 'com.example.seminarium.RunnerTests',
  );
}
